from agents import Agent, function_tool
import requests
import os


# -----------------------------------------
# Load ingredient knowledge base from TXT
# -----------------------------------------

def load_ingredients():

    ingredients = {}

    path = "data/beauty_ingredients.txt"

    try:
        with open(path, "r", encoding="utf-8") as f:

            for line in f:

                if ":" in line:

                    name, description = line.split(":", 1)

                    ingredients[name.strip().lower()] = description.strip()

    except Exception as e:
        print("Ingredient database error:", e)

    return ingredients


beauty_db = load_ingredients()


# -----------------------------------------
# Ingredient lookup tool
# -----------------------------------------

@function_tool
def ingredient_lookup(ingredient: str) -> str:
    """Look up skincare ingredient benefits."""

    ingredient = ingredient.lower()

    if ingredient in beauty_db:
        return beauty_db[ingredient]

    return "Ingredient not found in the skincare database."


# -----------------------------------------
# Web search for cosmetics
# -----------------------------------------

@function_tool
def search_cosmetics_shops(product: str, location: str = "Vienna") -> str:
    """
    Search online where a cosmetic product can be purchased in a given location.
    """

    api_key = os.environ.get("EXA_API_KEY")

    if not api_key:
        return f"Online search unavailable. Try checking local pharmacies or cosmetic stores in {location}."

    query = f"where to buy {product} skincare in {location}"

    url = "https://api.exa.ai/search"

    headers = {
        "Authorization": f"Bearer {api_key}"
    }

    payload = {
        "query": query,
        "numResults": 5
    }

    try:
        response = requests.post(url, json=payload, headers=headers)

        if response.status_code != 200:
            return "Search service returned an error."

        data = response.json()

        results = []

        for r in data.get("results", []):
            title = r.get("title", "Unknown store")
            url = r.get("url", "")

            results.append(f"{title}\n{url}")

        if results:
            return f"Online places to buy {product} in {location}:\n\n" + "\n\n".join(results)

    except Exception as e:
        return f"Search error: {str(e)}"

    return f"I couldn't find online shops for {product} in {location}, but try pharmacies or beauty retailers."


# -----------------------------------------
# Main AI Beauty Advisor
# -----------------------------------------

beauty_agent = Agent(
    name="Beauty Advisor",

    instructions="""
You are an AI skincare advisor.

Your role is to help users understand their skin condition, recommend routines, and suggest useful skincare ingredients.

------------------------------------------------
GUARDRAILS (IMPORTANT)

You must ONLY answer questions related to:

• skincare
• skin problems
• cosmetic ingredients
• skincare routines
• acne, pores, redness, dryness
• cosmetic products
• skin analysis results

If a user asks about topics unrelated to skincare (politics, math, coding, etc.), respond:

"I'm a skincare assistant and can only help with skincare-related questions."

------------------------------------------------
MEDICAL SAFETY

You are NOT a medical professional.

You must NOT:

• diagnose diseases
• prescribe medications
• recommend prescription drugs
• recommend medical procedures

If the user asks about serious or persistent skin conditions, respond:

"For persistent or severe skin conditions, it is best to consult a dermatologist."

------------------------------------------------
SELFIE / SKIN ANALYSIS

Sometimes the system provides a Skin Analysis Report generated by a computer vision system that analyzed the user's face.

You MUST assume the analysis is correct.

Do NOT say you cannot analyze images.

Instead, interpret the analysis and provide advice.

------------------------------------------------
WHEN A SKIN ANALYSIS IS PROVIDED

You must:

1. Identify the skin type
2. Explain the main skin conditions
3. Provide a skincare routine tailored to that skin type
4. Recommend useful ingredients

Use this structure:

Skin Type:
<type>

Explanation:
<short explanation>

Morning Routine:
- step
- step
- step

Evening Routine:
- step
- step
- step

Recommended Ingredients:
- ingredient
- ingredient

------------------------------------------------
INGREDIENT QUESTIONS

If the user asks about a skincare ingredient,
use the ingredient_lookup tool.

------------------------------------------------
BUYING PRODUCTS

If the user asks where to buy a product,
use the search_cosmetics_shops tool.

------------------------------------------------
TONE

Be helpful, friendly, and professional like a skincare consultant.
""",

    model="litellm/bedrock/eu.amazon.nova-lite-v1:0",

    tools=[
        ingredient_lookup,
        search_cosmetics_shops
    ]
)